name: weapp
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.2
  fluttertoast: ^8.0.9
  flutter_svg: ^1.0.3
  flutter_spinkit: ^5.1.0
  tab_container: ^2.0.0
  photo_view: ^0.14.0
  image_picker: ^0.8.5+3
  syncfusion_flutter_sliders: ^20.1.52
  dio: ^4.0.6
  path_provider: ^2.0.10
  sqflite: ^2.0.2+1
  permission_handler: ^10.0.0
  masonry_grid: ^1.0.0
  google_maps_flutter: ^2.1.5
  flutter_polyline_points: ^1.0.0
  location: ^4.4.0
  flutter_google_places: ^0.3.0
  flutter_email_sender: ^5.1.0
  flutter_sms: ^2.3.2
  mailer: ^5.1.1
  firebase_auth: ^3.3.18
  cloud_firestore: ^3.1.15
  google_sign_in: ^5.3.1
  firebase_core: ^1.17.0
  carousel_slider: ^4.1.1
  geocoding: ^2.0.4
  google_api_headers: ^1.3.0-dev.0
  flutter_staggered_animations: ^1.0.0
  lazy_load_scrollview: ^1.3.0
  audioplayers: ^1.0.1
  flutter_facebook_auth: ^4.3.4
  on_audio_query: ^2.6.1
  get: ^4.6.5
  audio_video_progress_bar: ^0.10.0
  intl: ^0.17.0
  shared_preferences: ^2.0.15
  hive: ^2.2.1
  hive_flutter: ^1.1.0
  photo_manager: ^2.1.1
  video_player: ^2.4.2
  share_plus: ^4.0.4
  flutter_share_me: ^1.3.0
  social_share: ^2.2.1
  google_mobile_ads: ^1.2.0
  facebook_audience_network: ^1.0.1
  # audio_waveforms: ^0.1.1
  camera: 0.9.7+1
  # video_thumbnail: 0.4.6
  visibility_detector: ^0.3.3
  flutter_inapp_purchase: ^5.1.2
  
  

  


  

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  # flutter_lints: ^1.0.0
  url_launcher: ^6.1.2

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
   - assets/svg/
   - assets/images/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: jkr
      fonts:
        - asset: assets/fonts/PlusJakartaDisplay-Regular.otf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: jkb
      fonts:
        - asset: assets/fonts/PlusJakartaText-Bold.otf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
